### ISSUE TITLE
1.5.1 breaks DirectoryWatcher::reset()

### ISSUE THREAD

**Issue by redood** [TwP/directory_watcher#23]
DirectoryWatcher still has the reset() method which calls reset() on @scanner.

However seems like Scanner no longer has a reset() method.
Was working fine on 1.4.1.

```
Exception (NoMethodError):  undefined method `reset' for # <DirectoryWatcher::Scanner:0x0000000194ae98>
/usr/lib/ruby/gems/1.9.1/gems/directory_watcher-1.5.1/lib/directory_watcher.rb:576:in `reset'
```
